steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcp-release-notes-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
  
  # Create a latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:latest']
  
  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:latest']

images:
  - 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gcp-release-notes-dashboard:latest'

timeout: '1200s' 